services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  WapplerSystems\PowermailBodymatcher\:
    resource: "../Classes/*"
    exclude:
      - "../Classes/Domain/Model/*"
      - "../Classes/Domain/Validator/SpamShield/*"
